server:
  port: 81
spring:
  rabbitmq:
    host: 39.106.19.2
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual #消费者手动确认消息
        prefetch: 1 #限制每次接收一条消息

swagger:
  exclude-path: /ops/**, /error